n = input('Digite algo na tela: ')
print('Qual o tipo primitivo desse valor? ',type(n))
print('É alfabético? ',n.isalpha())
print('É alfanumérico? ',n.isalnum())
print('É númerico? ',n.isnumeric())
print('Está em letras maiúscula? ',n.isupper())
print('Tem somente espaços? ',n.isspace())
print('Está em letras minúsculas? ',n.islower())
print('Está capitalizada? ',n.istitle())
